0.1.10

diff --git a/bin/sparky-chrooter b/bin/sparky-chrooter
--- a/bin/sparky-chrooter
+++ b/bin/sparky-chrooter
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 # Created by Paweł "pavroo" Pijanowski <pavroo@onet.eu> 2015/08/29
-# Last update 2016/11/27
-# Copyright 2015, 2016 Under the GNU GPL2 License
+# Copyright 2015-2018 Under the GNU GPL2 License
+# Last update 2018/03/29
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-chrooter"
@@ -25,7 +25,6 @@ else
 fi
 
 testroot="`whoami`"
-
 if [ "$testroot" != "root" ]; then
     /usr/bin/remsu $0 &
 fi
@@ -39,10 +38,11 @@ YESNO=" --button=$LOCAL3:0 --button=$LOCAL4:1 "
 MSGBOX=" --button=Ok:0 "
 CLOSE=" --button=$LOCAL5:0 "
 TITLETEXT="$LOCAL6"
-if [ -f /opt/sparky/sparky-xterm ]; then
-. /opt/sparky/sparky-xterm
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 # if not Live system just quit, don't launch the application
@@ -149,7 +149,7 @@ mount -o bind /sys /mnt/sys
 mount -o bind /tmp /mnt/tmp
 
 # chroot
-$SPARKYXTERM -e "chroot /mnt /bin/bash"
+$SPARKYXTERM "chroot /mnt /bin/bash"
 sleep 1
 
 # keep the window open until finishing your job in chrooted environment
